"""ajoute training_session_matches (tirage avant pronostic)

Revision ID: 462b0d65097b
Revises: beb01f3168da
Create Date: 2026-07-13 01:36:53.050941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '462b0d65097b'
down_revision: Union[str, None] = 'beb01f3168da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_session_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_session_id', sa.Integer(), nullable=False),
    sa.Column('historical_match_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['historical_match_id'], ['historical_matches.id'], ),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_session_id', 'historical_match_id', name='uq_training_session_matches_session_match')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_session_matches')
    # ### end Alembic commands ###
