"""simulation mode alternatif (graine, seed)

Revision ID: 4a1f86318170
Revises: 7965c4a5876b
Create Date: 2026-07-13 03:48:06.866208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a1f86318170'
down_revision: Union[str, None] = '7965c4a5876b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alembic ne détecte pas les ajouts de valeur sur un type enum PostgreSQL existant :
    # à faire à la main. ADD VALUE ne peut pas être utilisée dans la même transaction que
    # celle qui l'exécute, mais peut être ajoutée sans problème (PostgreSQL 12+).
    op.execute("ALTER TYPE simulation_mode ADD VALUE IF NOT EXISTS 'ALTERNATE'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_runs', sa.Column('seed', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_runs', 'seed')
    # ### end Alembic commands ###
    # PostgreSQL ne permet pas de retirer une valeur d'un type enum : 'ALTERNATE' reste
    # disponible après un downgrade (limitation connue, sans impact tant qu'elle n'est
    # utilisée par aucune ligne).
