"""simulation realiste (mode, gel des resultats reels)

Revision ID: 7965c4a5876b
Revises: f37a0248eccc
Create Date: 2026-07-13 03:31:41.436349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7965c4a5876b'
down_revision: Union[str, None] = 'f37a0248eccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


simulation_mode_enum = sa.Enum('REALISTIC', name='simulation_mode')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_match_results', sa.Column('winner_team_id', sa.Integer(), nullable=True))
    op.add_column('simulation_match_results', sa.Column('is_frozen_real_result', sa.Boolean(), nullable=False))
    op.create_foreign_key(
        'fk_simulation_match_results_winner_team_id', 'simulation_match_results', 'teams', ['winner_team_id'], ['id']
    )
    # add_column ne crée pas le type enum PostgreSQL (contrairement à create_table) : il
    # faut le créer explicitement avant de l'utiliser.
    simulation_mode_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('simulation_runs', sa.Column('mode', simulation_mode_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_runs', 'mode')
    simulation_mode_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_constraint('fk_simulation_match_results_winner_team_id', 'simulation_match_results', type_='foreignkey')
    op.drop_column('simulation_match_results', 'is_frozen_real_result')
    op.drop_column('simulation_match_results', 'winner_team_id')
    # ### end Alembic commands ###
