"""ajoute round_of_32 et teams.group_name

Revision ID: b6eb2ae6fdd0
Revises: 0a1c67cbbd3f
Create Date: 2026-07-12 21:10:36.579444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6eb2ae6fdd0'
down_revision: Union[str, None] = '0a1c67cbbd3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alembic autogenerate ne détecte pas les changements de valeurs d'un type ENUM
    # PostgreSQL existant : ajouté manuellement pour le format 48 équipes (2026).
    # SQLAlchemy stocke le nom du membre Python (ex. "GROUP"), pas sa valeur ("group") :
    # la nouvelle valeur doit suivre la même convention que les valeurs déjà en base.
    op.execute("ALTER TYPE match_phase ADD VALUE IF NOT EXISTS 'ROUND_OF_32'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('group_name', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'group_name')
    # ### end Alembic commands ###
    # PostgreSQL ne permet pas de retirer une valeur d'un type ENUM : la valeur
    # 'round_of_32' reste dans le type match_phase après un downgrade.
