"""matches: equipes finales nullables, placeholders, num

Revision ID: ba5c0f982d89
Revises: b6eb2ae6fdd0
Create Date: 2026-07-12 22:05:34.075220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba5c0f982d89'
down_revision: Union[str, None] = 'b6eb2ae6fdd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('home_placeholder', sa.String(length=50), nullable=True))
    op.add_column('matches', sa.Column('away_placeholder', sa.String(length=50), nullable=True))
    op.add_column('matches', sa.Column('num', sa.Integer(), nullable=True))
    op.alter_column('matches', 'home_team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('matches', 'away_team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint('uq_matches_num', 'matches', ['num'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_matches_num', 'matches', type_='unique')
    op.alter_column('matches', 'away_team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('matches', 'home_team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('matches', 'num')
    op.drop_column('matches', 'away_placeholder')
    op.drop_column('matches', 'home_placeholder')
    # ### end Alembic commands ###
