"""matches: prolongation, tirs au but, vainqueur

Revision ID: de1913a79a36
Revises: ba5c0f982d89
Create Date: 2026-07-12 22:35:10.325523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de1913a79a36'
down_revision: Union[str, None] = 'ba5c0f982d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('extra_time_home_score', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('extra_time_away_score', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('penalties_home_score', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('penalties_away_score', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('winner_team_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_matches_winner_team_id_teams', 'matches', 'teams', ['winner_team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_matches_winner_team_id_teams', 'matches', type_='foreignkey')
    op.drop_column('matches', 'winner_team_id')
    op.drop_column('matches', 'penalties_away_score')
    op.drop_column('matches', 'penalties_home_score')
    op.drop_column('matches', 'extra_time_away_score')
    op.drop_column('matches', 'extra_time_home_score')
    # ### end Alembic commands ###
