"""ajoute contexte sportif (entraineurs, compositions)

Revision ID: f37a0248eccc
Revises: 462b0d65097b
Create Date: 2026-07-13 02:48:42.560483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37a0248eccc'
down_revision: Union[str, None] = '462b0d65097b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('formation', sa.String(length=20), nullable=True),
    sa.Column('api_fixture_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team_id', name='uq_lineups_match_team')
    )
    op.create_table('lineup_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lineup_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('shirt_number', sa.Integer(), nullable=True),
    sa.Column('is_starter', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lineup_id'], ['lineups.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lineup_id', 'player_id', name='uq_lineup_players_lineup_player')
    )
    op.add_column('players', sa.Column('api_football_player_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_players_api_football_player_id', 'players', ['api_football_player_id'])
    op.add_column('teams', sa.Column('coach_name', sa.String(length=150), nullable=True))
    op.add_column('teams', sa.Column('coach_photo_url', sa.String(length=255), nullable=True))
    op.add_column('teams', sa.Column('api_football_team_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_teams_api_football_team_id', 'teams', ['api_football_team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_teams_api_football_team_id', 'teams', type_='unique')
    op.drop_column('teams', 'api_football_team_id')
    op.drop_column('teams', 'coach_photo_url')
    op.drop_column('teams', 'coach_name')
    op.drop_constraint('uq_players_api_football_player_id', 'players', type_='unique')
    op.drop_column('players', 'api_football_player_id')
    op.drop_table('lineup_players')
    op.drop_table('lineups')
    # ### end Alembic commands ###
